pipeline {
    agent none

    stages {
        stage('Test') {
            agent {
                docker {
                    reuseNode true
                    image 'pytest-playwright:latest'
                    args """
                        --name my-playwright-test
                        --network jenkins
                        --env DOCKER_HOST=tcp://docker:2376
                        --env DOCKER_CERT_PATH=/certs/client
                        --env DOCKER_TLS_VERIFY=1
                        --env TEST_EMAIL='valid@example.io'
                        --env TEST_PASSWORD='valid'
                        --volume /Users/youngh9822/learn/docker/jenkins-docker-certs:/certs/client
                        --volume /Users/youngh9822/learn/docker/jenkins-data:/var/jenkins_home
                        --volume Case1:Case1:rw'
                    """
                }
            }

            steps {
                sh 'pytest --html=/Case1/result/result.html --self-contained-html -m regression Case1'
            }
        }
    }
}