openapi: 3.0.0
info:
  version: 1.0.0
  title: HTTP and WebSocket APIs demonstrating the power of k6
  description: A simple API to demonstrate OpenAPI specification
  license: 
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'https://test-api.k6.io'
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []
paths:
# public apis
  /public/crocodiles:
    $ref: paths/public@crocodiles.yaml
  '/public/crocodiles/{id}':
    $ref: 'paths/public@crocodiles@{id}.yaml'
  
# registration and authentication
  /user/register:
    $ref: paths/user@register.yaml
  /auth/basic/login:
    $ref: paths/auth@basic@login.yaml

# private apis
  /my/crocodiles:
    $ref: paths/my@crocodiles.yaml
